import React from 'react';
import { Helmet } from 'react-helmet';
import { useTranslation } from 'react-i18next';
import { motion } from 'framer-motion';
import MainHeader from '@/components/MainHeader';
import Footer from '@/components/sections/Footer';

const TermsOfServicePage = () => {
  const { t } = useTranslation('common');

  const content = {
    title: t('terms_of_service_title'),
    lastUpdated: "July 9, 2025",
    sections: [
      {
        title: "1. Acceptance of Terms",
        text: "By accessing or using the Exodus Intelligence platform, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our services."
      },
      {
        title: "2. Description of Service",
        text: "Exodus Intelligence provides a platform that uses Artificial Intelligence to offer personalized recommendations and analysis on migration routes. The service is for informational purposes only and does not constitute binding legal advice."
      },
      {
        title: "3. User Responsibilities",
        text: "You are responsible for the accuracy of the information you provide. You agree not to use the platform for any illegal or unauthorized purpose. Misuse of the platform, including providing false information or attempting to manipulate the AI, may result in the suspension or termination of your account."
      },
      {
        title: "4. Limitation of Liability",
        text: "The recommendations generated by our AI are based on the data provided and available legislation. Exodus Intelligence is not responsible for the final outcome of any migration process. The platform is a guidance tool, and all final decisions should be made in consultation with qualified legal professionals."
      },
      {
        title: "5. Intellectual Property",
        text: "All content on the platform, including the design, text, graphics, and the Migratory Score™ methodology, is the exclusive property of Exodus Intelligence Inc. and is protected by intellectual property laws."
      },
      {
        title: "6. Modification of Terms",
        text: "We reserve the right to modify these terms at any time. We will notify you of any changes by posting the new terms on this page. Your continued use of the service after any such changes constitutes your acceptance of the new terms."
      }
    ]
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="bg-slate-900 text-white min-h-screen"
    >
      <Helmet>
        <title>{content.title} - Exodus Intelligence</title>
      </Helmet>
      <MainHeader />
      <main className="py-24 px-4">
        <div className="max-w-4xl mx-auto">
          <motion.h1 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-5xl font-bold text-center mb-4 bg-gradient-to-r from-purple-400 to-cyan-400 bg-clip-text text-transparent"
          >
            {content.title}
          </motion.h1>
          <p className="text-center text-gray-500 mb-12">Last Updated: {content.lastUpdated}</p>

          <div className="space-y-8 text-gray-300 leading-relaxed">
            {content.sections.map((section, index) => (
              <motion.section
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, amount: 0.5 }}
                transition={{ duration: 0.5 }}
              >
                <h2 className="text-2xl font-bold text-gray-100 mb-3">{section.title}</h2>
                <p>{section.text}</p>
              </motion.section>
            ))}
          </div>
        </div>
      </main>
      <Footer />
    </motion.div>
  );
};

export default TermsOfServicePage;